name: Push events to Branches
on: 
 workflow_dispatch:
  inputs:
   parm1:
    description: "Test input"
    default: "Hello World"
jobs:
   show-info:
     runs-on: ubuntu-latest
     steps:
     - name: Test Job
       run: | 
        echo "Sample Job : ${{github.event.inputs.parm1}}"
